apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc-dev
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-dev
  template:
    metadata:
      labels:
        app: minio-dev
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  name: gradsystem-config-dev
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gradsystem-secret-dev
                  key: MINIO_ROOT_PASSWORD
          command:
            - "minio"
            - "server"
            - "/data"
            - "--console-address"
            - ":9001"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-pvc-dev

---
apiVersion: v1
kind: Service
metadata:
  name: minio-service-dev
  namespace: dev
spec:
  selector:
    app: minio-dev
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP

---
apiVersion: batch/v1
kind: Job
metadata:
  name: createbuckets-dev
  namespace: dev
spec:
  template:
    metadata:
      labels:
        app: createbuckets-dev
    spec:
      restartPolicy: Never
      containers:
        - name: createbuckets
          image: minio/mc:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep 15;
              /usr/bin/mc alias set myminio http://minio-service-dev:9000 "$(MINIO_ROOT_USER)" "$(MINIO_ROOT_PASSWORD)";
              /usr/bin/mc mb myminio/grading-files --ignore-existing;
              /usr/bin/mc policy set public myminio/grading-files;
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  name: gradsystem-config-dev
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gradsystem-secret-dev
                  key: MINIO_ROOT_PASSWORD
          resources:
            limits:
              memory: "128Mi"
              cpu: "125m"
            requests:
              memory: "64Mi"
              cpu: "62m" 