apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradsystem
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradsystem
  template:
    metadata:
      labels:
        app: gradsystem
    spec:
      containers:
      - name: gradsystem
        env:
        - name: BUILD_VERSION
          value: "__APP_VERSION__"  
        - name: BUILD_BRANCH
          value: "__APP_BRANCH__"   
        - name: BUILD_COMMIT
          value: "__APP_COMMIT_HASH__"  
        - name: BUILD_TIME
          value: "__APP_BUILD_TIME__"   
        - name: REDIS_HOST
          value: "redis"    
        - name: REDIS_PORT
          value: "6379"     
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: REDIS_PASSWORD
        - name: MINIO_ENDPOINT
          value: "minio-service"
        - name: MINIO_PORT
          value: "9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: gradsystem-config
              key: MINIO_ROOT_USER
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: MINIO_ROOT_PASSWORD
        - name: OLLAMA_API_URL
          valueFrom:
            configMapKeyRef:
              name: gradsystem-config
              key: OLLAMA_API_URL
        - name: OLLAMA_API_KEY
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: OLLAMA_API_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: DATABASE_URL
        - name: THEME_SECRET
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: THEME_SECRET        
        - name: AUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: AUTH_SECRET
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: GOOGLE_CLIENT_SECRET
        - name: GOOGLE_REDIRECT_URI
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: GOOGLE_REDIRECT_URI
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: GEMINI_API_KEY
        - name: AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: AUTH_KEY
        - name: PDF_PARSER_API_URL
          valueFrom:
            configMapKeyRef:
              name: gradsystem-config
              key: PDF_PARSER_API_URL
        - name: GEMINI_API_KEY2
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: GEMINI_API_KEY2
        - name: GEMINI_API_KEY3
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: GEMINI_API_KEY3
        - name: PRISMA_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: gradsystem-config
              key: PRISMA_LOG_LEVEL
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gradsystem-secret
              key: OPENAI_API_KEY
        # - name: NODE_ENV
        #   valueFrom:
        #     configMapKeyRef:
        #       name: gradsystem-config
        #       key: NODE_ENV
        image: chunchiehdev/gradsystem:master  
        imagePullPolicy: Always  
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
