auth:
  enabled: true
  admin:
    username: admin
    password: admin123  
    token: Sxqxt9qEciT2nsQufVXv       

influxdb:
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"  

initdbScripts:
  db-init.sh: |
    #!/bin/bash
    influx bucket create -n k6 --org my-org --retention 0
    influx org create -n my-org
    influx token create --read-bucket k6 --write-bucket k6 --org my-org -o my-org
persistence:
  enabled: true
  size: 8Gi
