# deployment-dev.yaml
# Deployments for grading-pdf API and Worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grading-pdf-api-dev
  namespace: grading-pdf-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grading-pdf-api-dev
  template:
    metadata:
      labels:
        app: grading-pdf-api-dev
    spec:
      containers:
      - name: grading-pdf-api-dev
        image: chunchiehdev/grading-pdf:master
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: grading-pdf-config-dev
              key: REDIS_URL
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: grading-pdf-config-dev
              key: APP_MODE
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: grading-pdf-config-dev
              key: LOG_LEVEL
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grading-pdf-worker-dev
  namespace: grading-pdf-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grading-pdf-worker-dev
  template:
    metadata:
      labels:
        app: grading-pdf-worker-dev
    spec:
      containers:
      - name: grading-pdf-worker-dev
        image: chunchiehdev/grading-pdf:master
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: grading-pdf-config-dev
              key: REDIS_URL
        - name: WORKER_CONCURRENCY
          valueFrom:
            configMapKeyRef:
              name: grading-pdf-config-dev
              key: WORKER_CONCURRENCY
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: grading-pdf-config-dev
              key: LOG_LEVEL
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        command: ["celery", "-A", "app.worker.celery_app", "worker", "--loglevel=info", "--concurrency=4"]
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "200m"
